version: '3'

services:

  redzilla:
    build: .
    # image: opny/redzilla
    environment:
      # default compose network name
      REDZILLA_NETWORK: redzilla_redzilla
      REDZILLA_DOMAIN: redzilla.localhost
    networks:
      - redzilla
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data

networks:
  redzilla:
    driver: bridge
